
/*CREATE DATABASE MusicCollection
GO*/

USE MusicCollection

CREATE TABLE MusicGroups
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Styles
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Playlists
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Musicians
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL,
    Age INT NOT NULL,
    Instrument NVARCHAR(MAX) NOT NULL,
    MusicGroupID INT FOREIGN KEY REFERENCES MusicGroups(ID) NOT NULL
)

CREATE TABLE Albums
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    MusicGroupID INT FOREIGN KEY REFERENCES MusicGroups(ID) NOT NULL,
    PlaylistID INT FOREIGN KEY REFERENCES Playlists(ID)
)

CREATE TABLE Songs
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,    
    StyleID INT FOREIGN KEY REFERENCES Styles(ID) NOT NULL,
    AlbumID INT FOREIGN KEY REFERENCES Albums(ID)
)

CREATE TABLE SongsArchive
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    SongID INT FOREIGN KEY REFERENCES Songs(ID) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(), 
)