
/*CREATE DATABASE SportsShop
GO*/

USE SportsShop

CREATE TABLE Goods
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR (MAX) NOT NULL,
    ExpirationDate DATE NOT NULL,
    Quantity INT NOT NULL,
    Price MONEY NOT NULL 
)

CREATE TABLE Sellers
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL,
    Age INT NOT NULL,
    EmploymentDate DATE CHECK (EmploymentDate >= '01.01.2000') NOT NULL,
    Salary MONEY CHECK (Salary > 0) NOT NULL
)

CREATE TABLE Customers
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL,
    Age INT NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Email NVARCHAR(20) NOT NULL
)

CREATE TABLE Storages
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    [Address] NVARCHAR(MAX) NOT NULL,
    GoodsID INT FOREIGN KEY REFERENCES Goods(ID) NOT NULL
)

CREATE TABLE GoodsArchive
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    GoodsID INT FOREIGN KEY REFERENCES Goods(ID) NOT NULL,
    CustomerID INT FOREIGN KEY REFERENCES Customers(ID) NOT NULL,
    SellerID INT FOREIGN KEY REFERENCES Sellers(ID) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)

CREATE TABLE WorkersArchive
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    SellerID INT FOREIGN KEY REFERENCES Sellers(ID) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)