
/*CREATE DATABASE Academy
GO*/
USE Academy;

CREATE TABLE Faculties
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Dean NVARCHAR(MAX) NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE Teachers
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    EmploymentDate DATE CHECK (EmploymentDate >= '01.01.1990') NOT NULL,
    IsAssistant BIT DEFAULT 0 NOT NULL,
    IsProfessor BIT DEFAULT 0 NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Position NVARCHAR(MAX) NOT NULL,
    Premium MONEY  DEFAULT 0 CHECK (Premium >= 0) NOT NULL,
    Salary MONEY CHECK (Salary > 0) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Departments
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Financing MONEY DEFAULT 0 CHECK (Financing >= 0) NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE Groups
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL,
    Rating INT CHECK (Rating BETWEEN 0 AND 5) NOT NULL,
    [Year] INT CHECK ([Year] BETWEEN 1 AND 5) NOT NULL
)