
CREATE DATABASE BarberShop
GO

USE BarberShop;

CREATE TABLE Services
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Price MONEY NOT NULL,
    [Time] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE BarberShops
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Popularity INT CHECK (Popularity BETWEEN 1 AND 5) NOT NULL
)

CREATE TABLE Barbers
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL,
    Age INT CHECK(Age BETWEEN 18 AND 65) NOT NULL,
    Experience INT NOT NULL,
    EmploymentDate DATE CHECK (EmploymentDate > '01.01.2000'),
    WorkingTime INT NOT NULL,
    ServiceID INT FOREIGN KEY REFERENCES Services(ID) NOT NULL,
    BarberShopID INT FOREIGN KEY REFERENCES BarberShops(ID) NOT NULL
)

CREATE TABLE BarbersSchedules
(
    ID INT PRIMARY KEY IDENTITY(1, 1),
    WorkDate DATE NOT NULL,
    Week INT NOT NULL,
    BarberID INT FOREIGN KEY REFERENCES Barbers(ID) NOT NULL
)

CREATE TABLE Clients
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    BarberID INT FOREIGN KEY REFERENCES Barbers(ID) NOT NULL
)

CREATE TABLE FeedBacks
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Rating INT CHECK (Rating BETWEEN 1 AND 5) NOT NULL,
    [Description] NVARCHAR(MAX) NOT NULL,
    ClientID INT FOREIGN KEY REFERENCES Clients(ID) NOT NULL,
    BarberID INT FOREIGN KEY REFERENCES Barbers(ID) NOT NULL
)

CREATE TABLE ClientServices
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    ClientID INT FOREIGN KEY REFERENCES Clients(ID) NOT NULL,
    ServiceID INT FOREIGN KEY REFERENCES Services(ID) NOT NULL
)

CREATE TABLE ServicesArchives
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    ClientID INT FOREIGN KEY REFERENCES Clients(ID) NOT NULL,
    ServiceID INT FOREIGN KEY REFERENCES Services(ID) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
)