
/*CREATE DATABASE Academy
GO*/

USE Academy

CREATE TABLE Subjects
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Teachers
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Salary MONEY CHECK (Salary > 0) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Faculties
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Departments
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    Financing MONEY CHECK (Financing >= 0) DEFAULT 0 NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL,
    FacultyID INT FOREIGN KEY REFERENCES Faculties(ID) NOT NULL
);

CREATE TABLE Lectures
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    DayOfWeek INT CHECK (DayOfWeek BETWEEN 1 AND 7) NOT NULL,
    LectureRoom NVARCHAR(MAX) NOT NULL,
    SubjectID INT FOREIGN KEY REFERENCES Subjects(ID) NOT NULL,
    TeacherID INT FOREIGN KEY REFERENCES Teachers(ID) NOT NULL
);

CREATE TABLE Groups
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(10) NOT NULL UNIQUE,
    [Year] INT NOT NULL CHECK ([Year] BETWEEN 1 AND 5),
    DepartmentID INT NOT NULL FOREIGN KEY REFERENCES Departments(ID)
);

CREATE TABLE GroupsLectures
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    GroupID INT NOT NULL FOREIGN KEY REFERENCES Groups(ID),
    LectureID INT NOT NULL FOREIGN KEY REFERENCES Lectures(ID)
);