
/*CREATE DATABASE Academy
GO*/

USE Academy

CREATE TABLE Teachers
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL
)

CREATE TABLE Assistans
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    TeacherID INT FOREIGN KEY REFERENCES Teachers(ID) NOT NULL
)

CREATE TABLE Deans
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    TeacherID INT FOREIGN KEY REFERENCES Teachers(ID) NOT NULL
)

CREATE TABLE Heads
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    TeacherID INT FOREIGN KEY REFERENCES Teachers(ID) NOT NULL
)

CREATE TABLE Curators
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    TeacherID INT FOREIGN KEY REFERENCES Teachers(ID) NOT NULL
)

CREATE TABLE Faculties
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Building INT CHECK (Building BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL,
    DeanID INT FOREIGN KEY REFERENCES Deans(ID) NOT NULL 
)

CREATE TABLE Departments
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Building INT CHECK (Building BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL,
    FacultyID INT FOREIGN KEY REFERENCES Faculties(ID) NOT NULL,
    HeadID INT FOREIGN KEY REFERENCES Heads(ID) NOT NULL
)

CREATE TABLE Groups
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(10) UNIQUE NOT NULL,
    [Year] INT CHECK ([Year] BETWEEN 1 AND 5) NOT NULL,
    DepartmentID INT FOREIGN KEY REFERENCES Departments(ID) NOT NULL,
)

CREATE TABLE GroupsCurators
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    CuratorID INT FOREIGN KEY REFERENCES Curators(ID) NOT NULL,
    GroupID INT FOREIGN KEY REFERENCES Groups(ID) NOT NULL,
)

CREATE TABLE LectureRooms
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Building INT CHECK (Building BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(10) UNIQUE NOT NULL
)

CREATE TABLE Subjects
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE Lectures
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    SubjectTD INT FOREIGN KEY REFERENCES Subjects(ID) NOT NULL,
    TeacherID INT FOREIGN KEY REFERENCES Teachers(ID) NOT NULL
)

CREATE TABLE Schedules
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    Class INT CHECK (Class BETWEEN 1 AND 8) NOT NULL,
    DayOfWeek INT CHECK (DayOfWeek BETWEEN 1 AND 7) NOT NULL,
    Week INT CHECK (Week BETWEEN 1 AND 52) NOT NULL,
    LectureID INT FOREIGN KEY REFERENCES Lectures(ID) NOT NULL,
    LectureRoomID INT FOREIGN KEY REFERENCES LectureRooms(ID) NOT NULL
)

CREATE TABLE GroupsLectures
(
    ID INT PRIMARY KEY IDENTITY NOT NULL,
    GroupID INT FOREIGN KEY REFERENCES Groups(ID) NOT NULL,
    LectureID INT FOREIGN KEY REFERENCES Lectures(ID) NOT NULL
)