
/*CREATE DATABASE Academy;
GO*/

USE Academy;

CREATE TABLE Subjects
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Teachers
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Salary MONEY NOT NULL CHECK (Salary > 0),
    Surname NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Lectures
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    LectureRoom NVARCHAR(MAX) NOT NULL,
    SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subjects(ID),
    TeacherID INT NOT NULL FOREIGN KEY REFERENCES Teachers(ID)
);

CREATE TABLE Faculties
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    Financing MONEY NOT NULL CHECK (Financing >= 0) DEFAULT 0,
    [Name] NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Departments
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    Financing MONEY NOT NULL CHECK (Financing >= 0) DEFAULT 0,
    [Name] NVARCHAR(100) NOT NULL UNIQUE,
    FacultyID INT NOT NULL FOREIGN KEY REFERENCES Faculties(ID)
);

CREATE TABLE Groups
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(10) NOT NULL UNIQUE,
    [Year] INT NOT NULL CHECK ([Year] BETWEEN 1 AND 5),
    DepartmentID INT NOT NULL FOREIGN KEY REFERENCES Departments(ID)
);

CREATE TABLE Curators
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    Surname NVARCHAR(MAX) NOT NULL
);

CREATE TABLE GroupsCurators
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    CuratorID INT NOT NULL FOREIGN KEY REFERENCES Curators(ID),
    GroupID INT NOT NULL FOREIGN KEY REFERENCES Groups(ID)
);

CREATE TABLE GroupsLectures
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    GroupID INT NOT NULL FOREIGN KEY REFERENCES Groups(ID),
    LectureID INT NOT NULL FOREIGN KEY REFERENCES Lectures(ID)
);